=== SteveHodge/assistantdm/party.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="AbilityType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Strength"/>
		<xs:enumeration value="Dexterity"/>
		<xs:enumeration value="Constitution"/>
		<xs:enumeration value="Intelligence"/>
		<xs:enumeration value="Wisdom"/>
		<xs:enumeration value="Charisma"/>
	</xs:restriction>
</xs:simpleType>

<xs:element name="AbilityScore">
	<xs:complexType>
		<xs:attribute name="type" type="AbilityType" use="required"/>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="AbilityScores">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="AbilityScore" maxOccurs="6"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:simpleType name="SaveType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Fortitude"/>
		<xs:enumeration value="Reflex"/>
		<xs:enumeration value="Will"/>
	</xs:restriction>
</xs:simpleType>

<xs:element name="Save">
	<xs:complexType>
		<xs:attribute name="type" type="SaveType" use="required"/>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="SavingThrows">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Save"/>
			<xs:element ref="Save"/>
			<xs:element ref="Save"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="Skill">
	<xs:complexType>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="ranks" type="xs:decimal" use="required"/>
		<xs:attribute name="misc" type="xs:int"/>
	</xs:complexType>
</xs:element>

<xs:element name="Skills">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Skill" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:simpleType name="ACComponentType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Dex"/>
		<xs:enumeration value="Armor"/>
		<xs:enumeration value="Shield"/>
		<xs:enumeration value="Size"/>
		<xs:enumeration value="Natural"/>
		<xs:enumeration value="Deflect"/>
		<xs:enumeration value="Dodge"/>
		<xs:enumeration value="Other"/>
	</xs:restriction>
</xs:simpleType>

<xs:element name="ACComponent">
	<xs:complexType>
		<xs:attribute name="type" type="ACComponentType" use="required"/>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
</xs:element>

<xs:element name="AC">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="ACComponent" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="Character">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="AbilityScores" maxOccurs="1"/>
			<xs:element name="HitPoints" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="maximum" type="xs:int" use="required"/>
					<xs:attribute name="wounds" type="xs:int"/>
					<xs:attribute name="non-lethal" type="xs:int"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Initiative" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="value" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element ref="SavingThrows" maxOccurs="1"/>
			<xs:element ref="Skills" maxOccurs="1"/>
			<xs:element ref="AC" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>

<!-- =========== Party structure =========== -->
<xs:element name="Party">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Member" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- =========== Top-Level Structure =========== -->

<xs:element name="Characters">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Character" maxOccurs="unbounded"/>
			<xs:element ref="Party" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== SteveHodge/assistantdm/party_backup.xml
<?xml version="1.0" encoding="UTF-8"?>

<Party xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="party.xsd">
    <Character name="Obsidian Sundark">
        <AbilityScores>
            <AbilityScore type="Strength" value="8"/>
            <AbilityScore type="Dexterity" value="16"/>
            <AbilityScore type="Constitution" value="20"/>
            <AbilityScore type="Intelligence" value="20"/>
            <AbilityScore type="Wisdom" value="14"/>
            <AbilityScore type="Charisma" value="10"/>
        </AbilityScores>
        <HitPoints maximum="42" wounds="17" non-lethal="10"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="4"/>
            <Save type="Reflex" value="6"/>
            <Save type="Will" value="7"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="0"/>
            <Skill type="Knowledge (Arcana)" value="8"/>
            <Skill type="Knowledge (History)" value="3"/>
            <Skill type="Knowledge (Local)" value="2"/>
            <Skill type="Knowledge (Nobility)" value="3"/>
            <Skill type="Knowledge (Machinery)" value="7"/>
            <Skill type="Knowledge (Religion)" value="6"/>
            <Skill type="Knowledge (The Planes)" value="3"/>
            <Skill type="Spot" value="0"/>
            <Skill type="Knowledge (Dungeoneering)" value="4"/>
        </Skills>
        <AC>
            <ACComponent type="Dex" value="3"/>
            <ACComponent type="Size" value="1"/>
            <ACComponent type="Deflect" value="1"/>
        </AC>
    </Character>
    <Character name="FitzLoyal">
        <AbilityScores>
            <AbilityScore type="Strength" value="16"/>
            <AbilityScore type="Dexterity" value="18"/>
            <AbilityScore type="Constitution" value="17"/>
            <AbilityScore type="Intelligence" value="16"/>
            <AbilityScore type="Wisdom" value="8"/>
            <AbilityScore type="Charisma" value="12"/>
        </AbilityScores>
        <HitPoints maximum="55" wounds="10"/>
        <Initiative value="4"/>
        <SavingThrows>
            <Save type="Fortitude" value="2"/>
            <Save type="Reflex" value="7"/>
            <Save type="Will" value="-1"/>
        </SavingThrows>
        <Skills>
            <Skill type="Search" value="9"/>
            <Skill type="Knowledge (Local)" value="5"/>
            <Skill type="Gather Information" value="1"/>
            <Skill type="Spot" value="8"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="5"/>
            <ACComponent type="Shield" value="2"/>
            <ACComponent type="Dex" value="4"/>
        </AC>
    </Character>
    <Character name="Deadwood">
        <AbilityScores>
            <AbilityScore type="Strength" value="9"/>
            <AbilityScore type="Dexterity" value="14"/>
            <AbilityScore type="Constitution" value="15"/>
            <AbilityScore type="Intelligence" value="11"/>
            <AbilityScore type="Wisdom" value="18"/>
            <AbilityScore type="Charisma" value="7"/>
        </AbilityScores>
        <HitPoints maximum="50"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="6"/>
            <Save type="Reflex" value="3"/>
            <Save type="Will" value="6"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="6"/>
            <Skill type="Knowledge (nature)" value="13"/>
            <Skill type="Spellcraft" value="4"/>
            <Skill type="Move Silently" value="-3"/>
            <Skill type="Survival" value="7"/>
            <Skill type="Jump" value="-9"/>
            <Skill type="Gather Information" value="0"/>
            <Skill type="Escape Artist" value="-3"/>
            <Skill type="Craft (Woodworking)" value="1"/>
            <Skill type="Swim" value="-5"/>
            <Skill type="Hide" value="-3"/>
            <Skill type="Handle Animal" value="9"/>
            <Skill type="Spot" value="6"/>
            <Skill type="Balance" value="-3"/>
            <Skill type="Profession (Landscaping)" value="1"/>
            <Skill type="Ride" value="3"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="2"/>
            <ACComponent type="Shield" value="1"/>
            <ACComponent type="Dex" value="2"/>
        </AC>
    </Character>
    <Character name="Sir Tanndeth">
        <AbilityScores>
            <AbilityScore type="Strength" value="10"/>
            <AbilityScore type="Dexterity" value="10"/>
            <AbilityScore type="Constitution" value="10"/>
            <AbilityScore type="Intelligence" value="10"/>
            <AbilityScore type="Wisdom" value="10"/>
            <AbilityScore type="Charisma" value="10"/>
        </AbilityScores>
        <HitPoints maximum="22"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="8"/>
            <Save type="Reflex" value="3"/>
            <Save type="Will" value="5"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="-14"/>
            <Skill type="Search" value="-14"/>
            <Skill type="Handle Animal" value="-9"/>
            <Skill type="Gather Information" value="-11"/>
            <Skill type="Spot" value="-14"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="4"/>
            <ACComponent type="Shield" value="2"/>
            <ACComponent type="Dex" value="-1"/>
        </AC>
    </Character>
    <Character name="Heidi Himmler">
        <AbilityScores>
            <AbilityScore type="Strength" value="15"/>
            <AbilityScore type="Dexterity" value="14"/>
            <AbilityScore type="Constitution" value="18"/>
            <AbilityScore type="Intelligence" value="14"/>
            <AbilityScore type="Wisdom" value="18"/>
            <AbilityScore type="Charisma" value="11"/>
        </AbilityScores>
        <HitPoints maximum="22"/>
        <Initiative value="4"/>
        <SavingThrows>
            <Save type="Fortitude" value="7"/>
            <Save type="Reflex" value="2"/>
            <Save type="Will" value="6"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="0"/>
            <Skill type="Search" value="0"/>
            <Skill type="Knowledge (History)" value="1"/>
            <Skill type="Knowledge (Religion)" value="8"/>
            <Skill type="Spot" value="0"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="10"/>
            <ACComponent type="Shield" value="4"/>
            <ACComponent type="Dex" value="1"/>
        </AC>
    </Character>
</Party>

=== SteveHodge/assistantdm/Copy of party.xml
<?xml version="1.0" encoding="UTF-8"?>

<Party xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="party.xsd">
    <Character name="Obsidian Sundark">
        <HitPoints maximum="17"/>
        <Initiative value="5"/>
        <SavingThrows>
            <Save type="Fortitude" value="5"/>
            <Save type="Reflex" value="4"/>
            <Save type="Will" value="4"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="5"/>
            <Skill type="Search" value="4"/>
            <Skill type="Knowledge (Arcana)" value="7"/>
            <Skill type="Knowledge (History)" value="6"/>
            <Skill type="Knowledge (Local)" value="6"/>
            <Skill type="Knowledge (Nobility)" value="6"/>
            <Skill type="Knowledge (Machinery)" value="8"/>
            <Skill type="Knowledge (Religion)" value="6"/>
            <Skill type="Knowledge (The Planes)" value="6"/>
            <Skill type="Spot" value="3"/>
            <Skill type="Knowledge (Dungeoneering)" value="7"/>
        </Skills>
        <AC>
            <ACComponent type="Dex" value="2"/>
            <ACComponent type="Size" value="1"/>
        </AC>
    </Character>
    <Character name="FitzLoyal">
        <HitPoints maximum="16"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="2"/>
            <Save type="Reflex" value="7"/>
            <Save type="Will" value="-1"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="-1"/>
            <Skill type="Search" value="8"/>
            <Skill type="Knowledge (Local)" value="8"/>
            <Skill type="Gather Information" value="4"/>
            <Skill type="Spot" value="-1"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="3"/>
            <ACComponent type="Shield" value="1"/>
            <ACComponent type="Dex" value="4"/>
        </AC>
    </Character>
    <Character name="Deadwood">
        <HitPoints maximum="18"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="5"/>
            <Save type="Reflex" value="2"/>
            <Save type="Will" value="6"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="8"/>
            <Skill type="Gather Information" value="-2"/>
            <Skill type="Spot" value="9"/>
            <Skill type="Knowledge (Nature)" value="9"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="2"/>
            <ACComponent type="Shield" value="1"/>
            <ACComponent type="Dex" value="2"/>
        </AC>
    </Character>
    <Character name="Select Vera">
        <HitPoints maximum="11"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="6"/>
            <Save type="Reflex" value="-1"/>
            <Save type="Will" value="1"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="1"/>
            <Skill type="Search" value="1"/>
            <Skill type="Knowledge (Nobility)" value="6"/>
            <Skill type="Knowledge (Religion)" value="5"/>
            <Skill type="Gather Information" value="4"/>
            <Skill type="Spot" value="1"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="4"/>
            <ACComponent type="Shield" value="2"/>
            <ACComponent type="Dex" value="-1"/>
        </AC>
    </Character>
    <Character name="Heidi Himmler">
        <HitPoints maximum="12"/>
        <Initiative value="0"/>
        <SavingThrows>
            <Save type="Fortitude" value="6"/>
            <Save type="Reflex" value="2"/>
            <Save type="Will" value="5"/>
        </SavingThrows>
        <Skills>
            <Skill type="Listen" value="3"/>
            <Skill type="Search" value="2"/>
            <Skill type="Spot" value="3"/>
        </Skills>
        <AC>
            <ACComponent type="Armor" value="4"/>
            <ACComponent type="Shield" value="2"/>
        </AC>
    </Character>
</Party>

=== SteveHodge/assistantdm/Deadwood .xml
<?xml version="1.0" encoding="UTF-8"?>

<Party xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="party.xsd">
	<Character name="Deadwood &quot;The Uncaring One&quot;">
		<AbilityScores>
			<AbilityScore type="Strength" value="9"/>
			<AbilityScore type="Dexterity" value="14"/>
			<AbilityScore type="Constitution" value="15"/>
			<AbilityScore type="Intelligence" value="11"/>
			<AbilityScore type="Wisdom" value="18"/>
			<AbilityScore type="Charisma" value="7"/>
		</AbilityScores>
		<HitPoints maximum="50"/>
		<Initiative value="0"/>
		<SavingThrows>
			<Save type="Fortitude" value="6"/>
			<Save type="Reflex" value="3"/>
			<Save type="Will" value="6"/>
		</SavingThrows>
		<Skills>
			<Skill type="Balance" value="-3"/>
			<Skill type="Climb" value="-2"/>
			<Skill type="Craft (Woodworking)" value="1"/>
			<Skill type="Escape Artist" value="-3"/>
			<Skill type="Handle Animal" value="9"/>
			<Skill type="Hide" value="-3"/>
			<Skill type="Jump" value="-9"/>
			<Skill type="Knowledge (nature)" value="13"/>
			<Skill type="Listen" value="6"/>
			<Skill type="Move Silently" value="-3"/>
			<Skill type="Profession (Landscaping)" value="1"/>
			<Skill type="Ride" value="3"/>
			<Skill type="Spellcraft" value="4"/>
			<Skill type="Spot" value="6"/>
			<Skill type="Survival" value="7"/>
			<Skill type="Swim" value="-5"/>
		</Skills>
		<AC>
			<ACComponent type="Armor" value="2"/>
			<ACComponent type="Shield" value="1"/>
			<ACComponent type="Dex" value="2"/>
		</AC>
	</Character>
</Party>
